
# Sets the website to use local javascript/css only.
#local: "true"
local: "false"

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4040
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

